url: https://yameru-shoujoryo.onrender.com
db:
  host: 'postgresql://abmin:hpDSUghV9Nr74RD9dz0JqBWh7rejfzqD@dpg-d06g01ali9vc73ebbihg-a/abmin'
  port: 5432
  user: 'abmin'
  pass: 'hpDSUghV9Nr74RD9dz0JqBWh7rejfzqD'
  db: 'abmin'
redis:
  host: 'dpg-d06g01ali9vc73ebbihg-a'
  port: 6379
