services:
  - type: web
    name: yameru-shoujoryo
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: NODE_ENV=production CONFIG_PATH=.config/default.yml yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
            type: pserv
            name: misskey-db
            property: connectionString
      - key: REDIS_URL
        fromService:
            type: pserv
            name: misskey-redis
            property: connectionString
databases:
  - name: misskey-db
    databaseName: misskey
    user: misskey
  - name: misskey-redis
    ipAllowList: []
