url: postgresql://abmin:hpDSUghV9Nr74RD9dz0JqBWh7rejfzqD@dpg-d06g01ali9vc73ebbihg-a/abmin
port: 3000
db:
  host: localhost
  port: 5432
  db: misskey
  user: misskey
  pass: misskey-password
signToActivityPubGet: true
proxyProtocol: false
isCluster: false
clusterLimit: 10
